
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.4.33205.214
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "MakeFile", "MakeFile.vcxproj", "{A5AEF486-BA6D-4107-986D-41B8353B483A}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Debug|x64.ActiveCfg = Debug|x64
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Debug|x64.Build.0 = Debug|x64
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Debug|x86.ActiveCfg = Debug|Win32
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Debug|x86.Build.0 = Debug|Win32
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Release|x64.ActiveCfg = Release|x64
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Release|x64.Build.0 = Release|x64
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Release|x86.ActiveCfg = Release|Win32
		{A5AEF486-BA6D-4107-986D-41B8353B483A}.Release|x86.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {90961693-2023-4665-85B0-CF40CF9D669B}
	EndGlobalSection
EndGlobal
